apiVersion: v1
kind: Service
metadata:
  name: svc-stateful-myapp
  namespace: default
  labels:
    app: myapp
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None ##必须是无头服务
  selector:
    app: myapp-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
  namespace: default
spec:
  serviceName: svc-stateful-myapp
  replicas: 2
  selector:
    matchLabels:
      app: stateful-myapp-pod
  template:
    metadata:
      labels:
        app: stateful-myapp-pod
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        volumeMounts:
        - name: myappdata
          mountPath: /usr/share/nginx/html/ 
  volumeClaimTemplates:
  - metadata:
      name: myappdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi








