apiVersion: v1
kind: Service
metadata:
  name: redis-service-headless
  namespace: default
spec:
  selector:
    app: redis
    role: logstor
  clusterIP: "None"
  ports:
  - port: 6379
    targetPort: 6379

