apiVersion: v1
kind: Service
metadata:
  name: redis-service-nodeport
  namespace: default
spec:
  selector:
    app: myapp
  clusterIP: 10.99.99.99
  type: NodePort
  ports:
  - port: 80
    targetPort: 80

