apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    volumeMounts: 
    - name: html
      mountPath: /data/web/html/
  - name: busybox
    image: busybox:latest
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 9999"
    volumeMounts: 
    - name: html
      mountPath: /data/
  volumes:
  - name: html
    emptyDir: {}
    



