apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-app
      release: canary
  template:
    metadata:
      labels:
        app: dep-app
        release: canary
    spec:
      containers:
      - name: deployment-pod-myapp
        image: ikubernetes/myapp:v2
        ports:
        - name: http
          containerPort: 80
        
