---
- hosts: all
  gather_facts: False
  tasks:
      - name: uninstall k8s
        shell: |
          cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
          overlay
          br_netfilter
          EOF
        register: rst

      - name: command result
        debug:
          msg: "{{rst.stdout_lines}}"
  tags:
    - mod

- hosts: all
  gather_facts: False
  tasks:
      - name: uninstall k8s
        shell: |
          cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
          EOF
        register: rst

      - name: command result
        debug:
          msg: "{{rst.stdout_lines}}"
  tags:
    - net

