apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-file
  namespace: default
  labels:
    app: pod-cm-file
spec:
  containers:
  - name: pod-cm-file
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginxconf
      mountPath: /abc/
      readOnly: true
  volumes:
  - name: nginxconf
    configMap:
      name: nginx-config
